apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-test
spec:
  selector:
    matchLabels:
      app: websocket-test
  template:
    metadata:
      labels:
        app: websocket-test
    spec:
      imagePullPolicy: Always
      containers:
      - name: websocket-test
        image: quay.io/thikade/ws-echo:latest
        command: ["python3", "./server_k8s.py"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
        ports:
        - containerPort: 8000